// eslint-disable-next-line no-unused-vars
import { motion } from 'framer-motion';
import { ArrowRight, Code, Cpu, Zap } from 'lucide-react';
import Scene3D from '../../components/three/Scene3D';
import Typewriter from '../../components/ui/Typewriter';

const Feature = ({ icon, title, children }) => (
// ...existing code...
  <div className="flex items-start gap-4">
    <div className="mt-1 bg-white/10 p-2 rounded-lg">{icon}</div>
    <div>
      <h3 className="font-bold text-lg text-white">{title}</h3>
      <p className="text-white/70">{children}</p>
    </div>
  </div>
);

export default function Hero() {
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden bg-[#0a001f] px-4">
      {/* 3D Background & Grid */}
      <div className="absolute inset-0 z-0">
        <Scene3D />
        <div 
          className="absolute inset-0"
          style={{
            backgroundImage: 'radial-gradient(circle at center, rgba(127, 0, 255, 0.2) 0%, transparent 40%), linear-gradient(to bottom, transparent 0%, #0a001f 90%)',
          }}
        />
        <div 
          className="absolute inset-0"
          style={{
            backgroundImage: 'linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)',
            backgroundSize: '30px 30px',
          }}
        />
      </div>
      
      {/* Content */}
      <div className="relative z-10 w-full max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
        {/* Left Column: Text Content */}
        <div className="text-center md:text-left">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <h1 className="text-4xl md:text-6xl font-black text-white mb-6 leading-tight tracking-tighter">
              <Typewriter text="The Future of" speed={0.03} />
              <br />
              <span className="text-purple-400">
                <Typewriter text="Algorithm Visualization" delay={0.8} speed={0.04} />
              </span>
            </h1>
            <p className="text-lg md:text-xl mb-10 text-white/80 max-w-xl mx-auto md:mx-0">
              An interactive, immersive, and intelligent platform to master data structures and algorithms. Stop memorizing, start understanding.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="flex flex-col sm:flex-row gap-4 justify-center md:justify-start"
          >
            <motion.button
              whileHover={{ scale: 1.05, boxShadow: '0px 0px 30px rgba(99, 102, 241, 0.5)' }}
              whileTap={{ scale: 0.95 }}
              className="group px-8 py-4 bg-indigo-500 text-white rounded-full font-bold text-lg shadow-lg transition-all duration-300 flex items-center justify-center gap-2 cursor-pointer"
            >
              Start Learning Now
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </motion.button>
          </motion.div>
        </div>

        {/* Right Column: Features */}
        <motion.div 
          initial={{ opacity: 0, x: -100 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 1, delay: 0.4, ease: "easeOut" }}
          className="space-y-8 bg-white/5 backdrop-blur-md border border-white/10 p-8 rounded-2xl"
        >
          <Feature icon={<Zap className="text-yellow-300" />} title="Interactive 3D Visualizations">
            Engage with algorithms in a fully interactive 3D environment. Rotate, zoom, and step through every operation.
          </Feature>
          <Feature icon={<Code className="text-green-400" />} title="Real-time Code Sync">
            See your code come to life. The visualization updates in real-time as you write and edit your solutions.
          </Feature>
          <Feature icon={<Cpu className="text-sky-400" />} title="AI-Powered Explanations">
            Get unstuck with intelligent hints and explanations generated by our AI, tailored to your specific code.
          </Feature>
        </motion.div>
      </div>
    </section>
  );
}